name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install sphinx
        run: pip install sphinx
      
      - name: install graphviz and rclone
        run: sudo apt install graphviz rclone

      - name: Run make
        run: cd src && make

      - name: Save results as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: doc-build
          path: src/_build/

      - name: configure
        run: rclone config create my-remote webdav url ${{secrets.WEBDAV_URL}} vendor other user '${{secrets.WEBDAV_USER}}'  pass '${{secrets.WEBDAV_PASSWORD}}'

      - name: deploy
        run: "rclone sync src/_build my-remote:"

