name: Tests
on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  linkcheck:
    name: "Link check"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install sphinx
        run: pip install sphinx docutils==0.16
        # docutils should be < 0.17 for correct rendering. see https://stackoverflow.com/questions/67542699/readthedocs-sphinx-not-rendering-bullet-list-from-rst-file


      - name: install graphviz
        run: sudo apt install graphviz

      - name: Run linkcheck
        run: make linkcheck

      - name: Run build
        env: 
          SPHINXOPTS: "-W --keep-going -n"
        run: make

